# Generated by Django 5.2.8 on 2025-11-16 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
