# Generated by Django 5.2.8 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_clase_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='carrera',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
