# Generated by Django 5.2.8 on 2025-11-17 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_clase_carrera_clase_materia_alter_clase_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'ESTUDIANTE'}, related_name='clases_inscripto', to=settings.AUTH_USER_MODEL),
        ),
    ]
