# Generated by Django 5.2.8 on 2025-11-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_perfilestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('habilitado', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_config', to='aplicacion.clase')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('clase', 'level')},
            },
        ),
    ]
